spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/personalblog
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  flyway:
    mixed: true
    enabled: true
    locations: classpath:db/migration
    repair: true
    baseline-on-migrate: true